export const GETTING_USER = 'GETTING_USER';
export const GOT_USER = 'GOT_USER';
export const ERROR_GETTING_USER = 'ERROR_GETTING_USER';

export const GETTING_PLANTS = 'GETTING_PLANTS';
export const GOT_PLANTS = 'GOT_PLANTS';
export const ERROR_GETTING_PLANTS = 'ERROR_GETTING_PLANTS';

export const GETTING_PLANT = 'GETTING_PLANT';
export const GOT_PLANT = 'GOT_PLANT';
export const ERROR_GETTING_PLANT = 'ERROR_GETTING_PLANT';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

